name: Bump version, Build and Package

on:
  release:
    types:
      [released]
  

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v2.0.0     

      - name: Get version number
        id: version_num_set
        run: |
          echo "Version number from tag is ${{github.event.release.tag_name}}"
          $versionNum = "${{github.event.release.tag_name}}"
          $version_number = $versionNum -replace "v", ""
          echo "Numeric only from that is $version_number"
          echo "version=$version_number" >> $env:GITHUB_OUTPUT
        
      - name: Update installer config version
        run: |
            $content = Get-Content -Path Setup/RBP_Launcher.iss -Raw
            echo "Input installer config is $content"
            $content = $content -replace '#define AppVersion ".*"', '#define AppVersion "${{steps.version_num_set.outputs.version}}"'
            echo "Updated installer config is $content"
            Set-Content -Path Setup/RBP_Launcher.iss -Value $content

      - name: Update GlobalAssemblyInfo version
        run: |
            $version = "${{steps.version_num_set.outputs.version}}"
            $content = Get-Content -Path Common/GlobalAssemblyInfo.cs -Raw
            echo "Input GlobalAssemblyInfo is $content"
            $content = $content -replace 'AssemblyVersion\("\d+\.\d+\.\d+"\)', "AssemblyVersion(`"$version`")"
            $content = $content -replace 'AssemblyFileVersion\("\d+\.\d+\.\d+"\)', "AssemblyFileVersion(`"$version`")"
            $content = $content -replace 'AssemblyInformationalVersion\("\d+\.\d+\.\d+"\)', "AssemblyInformationalVersion(`"$version`")"
            echo "Updated GlobalAssemblyInfo is $content"
            Set-Content -Path Common/GlobalAssemblyInfo.cs -Value $content

      - name: Restore NuGet packages
        run: nuget restore "RBP Launcher.sln"
              
      - name: Build solution
        run: |
            msbuild "RBP Launcher.sln" /p:Configuration=Release 

      - name: Create installer file
        id: create_installer_file
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with: 
          path: Setup/RBP_Launcher.iss
          
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: Setup\Output\RBP_LauncherSetup_v${{ steps.version_num_set.outputs.version}}.exe
          asset_name: RBP_LauncherSetup_v${{ steps.version_num_set.outputs.version}}.exe
          asset_content_type: application/octet-stream
      
      - name: Commit and push if it changed
        run: |
          git diff
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git commit -am "Update version to ${{steps.version_num_set.outputs.version}} in installer config" && git push origin || echo "No changes to commit"
